#ifndef INSTRUCTIONS_H
#define INSTRUCTIONS_H

void fetch_instruction(void);
void exec_instructions(void);
void instr_null(void);
void instr_00E0(void);
void instr_00EE(void);
void instr_1NNN(void);
void instr_2NNN(void);
void instr_3XNN(void);
void instr_4XNN(void);
void instr_5XY0(void);
void instr_6XNN(void);
void instr_7XNN(void);
void instr_8XY0(void);
void instr_8XY1(void);
void instr_8XY2(void);
void instr_8XY3(void);
void instr_8XY4(void);
void instr_8XY5(void);
void instr_8XY6(void);
void instr_8XY7(void);
void instr_8XYE(void);
void instr_9XY0(void);
void instr_ANNN(void);
void instr_BNNN(void);
void instr_CXNN(void);
void instr_DXYN(void);
void instr_EX9E(void);
void instr_EXA1(void);
void instr_FX07(void);
void instr_FX0A(void);
void instr_FX15(void);
void instr_FX18(void);
void instr_FX1E(void);
void instr_FX29(void);
void instr_FX33(void);
void instr_FX55(void);
void instr_FX65(void);

#endif
